### ISSUE TITLE
Compilation error about ./build.sh

### ISSUE THREAD

**Issue by InYourFuture** [BayshoreNetworks/yextend#33]
I got the following errors when running the build.sh script

libs/bayshore_yara_wrapper.c:73:27: error: ‘TRUE’ undeclared here (not in a function)
 static int show_strings = TRUE;
                           ^
libs/bayshore_yara_wrapper.c:75:31: error: ‘FALSE’ undeclared here (not in a function)
 static int show_module_data = FALSE;

Makefile:529: recipe for target 'libs/bayshore_yara_wrapper.o' failed
make[1]: *** [libs/bayshore_yara_wrapper.o] Error 1
make[1]: Leaving directory '/home/hmj/yextend-master'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by InYourFuture** [comment]
i have already tried yara-3.9.0 and yara-3.8.1   
always following errors:

libs/bayshore_yara_wrapper.c:73:27: error: ‘TRUE’ undeclared here (not in a function)
 static int show_strings = TRUE;
                           ^
libs/bayshore_yara_wrapper.c:75:31: error: ‘FALSE’ undeclared here (not in a function)
 static int show_module_data = FALSE;
                               ^
libs/bayshore_yara_wrapper.c: In function ‘bayshore_yara_callback’:
libs/bayshore_yara_wrapper.c:299:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     mi->module_data = module_data->mapped_file.data;
                     ^
Makefile:529: recipe for target 'libs/bayshore_yara_wrapper.o' failed
make[1]: *** [libs/bayshore_yara_wrapper.o] Error 1
make[1]: Leaving directory '/home/hmj/yextend-master'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cecobayshore** [comment]
Hi - if you are trying to use newer versions of Yara (3.9.0 or 3.8.1) - there are branches within the project. Choose either branch yara-3.9.0 or branch yara-3.8.1. Branch yara-3.9.0 was lately modified to work with yara-3.10.0.
